"""File storage on the local filesystem.

The adapter a single-node deployment runs, and the one that makes the port's insistence on
opaque keys load-bearing rather than stylistic: a key taken from a filename would be a path
traversal here. The key is hashed into a filename precisely so that nothing about it can
escape the directory it was given.
"""

from __future__ import annotations

import asyncio
from hashlib import sha256
from pathlib import Path

from academy.application.errors import NotFoundError


class LocalFileStorage:
    """Bytes written under one directory, one file per key.

    Satisfies :class:`~academy.application.ports.outbound.file_storage.FileStorage`.

    Every method runs its filesystem call in a worker thread. The port is async because
    moving bytes to disk is I/O (ADR-0005), and a synchronous write inside an event loop
    would block every other request for the duration of an upload -- which for the large
    files this port exists to carry is precisely the case that matters.
    """

    def __init__(self, root: Path) -> None:
        """Store files under ``root``, creating it if it does not exist.

        Args:
            root: The directory to own. Everything in it is this adapter's; nothing outside
                it is reachable, whatever a key contains.
        """
        self._root = root
        self._root.mkdir(parents=True, exist_ok=True)

    async def put(self, key: str, data: bytes) -> None:
        """Store ``data`` under ``key``, replacing anything already there."""
        await asyncio.to_thread(self._path(key).write_bytes, data)

    async def get(self, key: str) -> bytes:
        """Retrieve the bytes stored under ``key``.

        Raises:
            NotFoundError: If nothing is stored there -- including the case a worker actually
                meets, where a sweep removed the payload between submission and execution.
        """
        path = self._path(key)
        try:
            return await asyncio.to_thread(path.read_bytes)
        except FileNotFoundError as error:
            raise NotFoundError('stored file', key) from error

    async def delete(self, key: str) -> None:
        """Remove whatever is stored under ``key``. Idempotent."""
        await asyncio.to_thread(self._path(key).unlink, True)

    def _path(self, key: str) -> Path:
        """Map an opaque key to a file inside the root.

        Hashed rather than used directly. The port says keys are opaque and generated by the
        application, and this is the adapter that would be exploited if that ever stopped
        being true: `../../etc/passwd` is a perfectly good dictionary key and a catastrophic
        filename. Hashing makes the guarantee structural instead of a promise.
        """
        return self._root / sha256(key.encode()).hexdigest()
