"""The initial schema: every table the application has, from an empty database.

Revision ID: 0001
Revises:
Create Date: 2026-08-31

Written by hand rather than autogenerated, and readable as a result. It is the first migration
of a repository that has never had a database, so there is no baseline to compare against and
nothing to preserve -- which makes this the one migration where getting the shape right is free.

Column types are the plain SQL ones, not the ``TypeDecorator``s from ``types.py``. A migration
describes storage; the decorators describe how the application converts value objects into that
storage, and a migration that imported them would break the day one is renamed.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Identifiers are stored as canonical UUID strings, so the same schema runs on SQLite and
# PostgreSQL and both hold identical bytes (ADR-0007). 36 characters is a UUID with hyphens.
UUID_LENGTH = 36


def upgrade() -> None:
    """Create every table."""
    op.create_table(
        'people',
        sa.Column('id', sa.String(UUID_LENGTH), nullable=False),
        sa.Column('email', sa.String(320), nullable=False),
        sa.Column('full_name', sa.String(200), nullable=False),
        sa.Column('birth_date', sa.Date(), nullable=False),
        # The four collection columns are JSON documents in a text column (ADR-0017): the
        # domain's value objects are `slots=True` and cannot be instrumented, and none of these
        # is addressable on its own.
        sa.Column('roles', sa.Text(), nullable=False),
        sa.Column('held_credentials', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_people')),
        sa.UniqueConstraint('email', name=op.f('uq_people_email')),
    )

    op.create_table(
        'course_sections',
        sa.Column('id', sa.String(UUID_LENGTH), nullable=False),
        sa.Column('subject_id', sa.String(UUID_LENGTH), nullable=False),
        sa.Column('term', sa.String(16), nullable=False),
        sa.Column('teacher_id', sa.String(UUID_LENGTH), nullable=False),
        sa.Column('enrollments', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_course_sections')),
    )
    op.create_index(op.f('ix_course_sections_teacher_id'), 'course_sections', ['teacher_id'])

    op.create_table(
        'academic_histories',
        # Keyed by the student: there is exactly one transcript per student and the domain has
        # no separate identifier for it.
        sa.Column('student_id', sa.String(UUID_LENGTH), nullable=False),
        sa.Column('entries', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('student_id', name=op.f('pk_academic_histories')),
    )

    op.create_table(
        'guardianships',
        sa.Column('id', sa.String(UUID_LENGTH), nullable=False),
        sa.Column('guardian_id', sa.String(UUID_LENGTH), nullable=False),
        sa.Column('ward_id', sa.String(UUID_LENGTH), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_guardianships')),
    )
    op.create_index(op.f('ix_guardianships_guardian_id'), 'guardianships', ['guardian_id'])
    op.create_index(op.f('ix_guardianships_ward_id'), 'guardianships', ['ward_id'])

    op.create_table(
        'configuration',
        # A single row under a fixed key. A table with one row and no key invites a second row
        # that nothing would ever read.
        sa.Column('key', sa.String(50), nullable=False),
        sa.Column('age_of_majority', sa.String(3), nullable=False),
        sa.PrimaryKeyConstraint('key', name=op.f('pk_configuration')),
    )

    op.create_table(
        'import_jobs',
        sa.Column('id', sa.String(UUID_LENGTH), nullable=False),
        sa.Column('kind', sa.String(32), nullable=False),
        sa.Column('storage_key', sa.String(256), nullable=False),
        sa.Column('submitted_by', sa.String(UUID_LENGTH), nullable=False),
        sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('status', sa.String(16), nullable=False),
        sa.Column('result', sa.Text(), nullable=True),
        sa.Column('failure_reason', sa.Text(), nullable=True),
        sa.Column('context', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs')),
    )
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'])
    op.create_index(op.f('ix_import_jobs_submitted_by'), 'import_jobs', ['submitted_by'])


def downgrade() -> None:
    """Drop every table, newest first.

    A downgrade nobody will run in production is still worth writing and worth testing: it is
    the only thing that proves the migration can be undone, and the test suite runs it from
    ``head`` to ``base`` on an empty database precisely so that the first person who needs it
    is not finding out then.
    """
    op.drop_index(op.f('ix_import_jobs_submitted_by'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_table('configuration')
    op.drop_index(op.f('ix_guardianships_ward_id'), table_name='guardianships')
    op.drop_index(op.f('ix_guardianships_guardian_id'), table_name='guardianships')
    op.drop_table('guardianships')
    op.drop_table('academic_histories')
    op.drop_index(op.f('ix_course_sections_teacher_id'), table_name='course_sections')
    op.drop_table('course_sections')
    op.drop_table('people')
