"""The blob storage port.

**Async** (ADR-0005): moving bytes to disk or to an object store is I/O.

This is the port that most clearly earns the label "adapter". Two implementations -- the
local filesystem and S3 -- differ in every operational respect and in none that the
application can observe, which is the property the whole architecture is arranged to produce.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class FileStorage(Protocol):
    """Somewhere to put bytes and get them back.

    Deliberately **byte-only**. The file's original name, its content type and its size are
    facts about an import job, and they live on :class:`~academy.application.jobs.ImportJob`;
    storage only ever moves opaque bytes under an opaque key. Adding a ``filename`` parameter
    here would put a second, competing source of truth behind the port, and the two would
    disagree the first time someone uploaded ``grades (1).xlsx``.
    """

    async def put(self, key: str, data: bytes) -> None:
        """Store ``data`` under ``key``, replacing anything already there.

        Keys are opaque to the caller and are generated by the application, never taken from
        a filename. That is not a style preference: a key derived from user input is a path
        traversal in the local adapter and a bucket-scoping bug in the S3 one.

        Args:
            key: Where to put it.
            data: The bytes to store.
        """
        ...

    async def get(self, key: str) -> bytes:
        """Retrieve the bytes stored under ``key``.

        Raises:
            NotFoundError: If nothing is stored under that key. A worker picking up a job
                whose payload has been swept away must fail the job with a clear reason,
                not receive an empty file and import nothing while reporting success.
        """
        ...

    async def delete(self, key: str) -> None:
        """Remove whatever is stored under ``key``.

        Idempotent: deleting an absent key is not an error. Cleanup runs after a job reaches
        a terminal state, and it must not fail merely because it is running for the second
        time.
        """
        ...
